-- Create marketing_calendar table
create table if not exists marketing_calendar (
  id bigint generated by default as identity primary key,
  month int not null,
  marketing_title text,
  event_title text,
  key_events text,
  purpose text,
  required_goods text,
  need_external_manpower text,
  estimated_budget text,
  expected_revenue text,
  expected_effect text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create input_data table to store user sessions
create table if not exists input_data (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  target_audience jsonb,
  competitors jsonb,
  our_analysis jsonb,
  environment_analysis jsonb,
  generated_strategy jsonb
);

-- Enable RLS (Row Level Security)
alter table marketing_calendar enable row level security;
alter table input_data enable row level security;

-- Create policies (Adjust based on your auth needs, here allowing public access for demo)
create policy "Enable read access for all users" on marketing_calendar for select using (true);
create policy "Enable insert access for all users" on input_data for insert with check (true);
create policy "Enable select access for all users" on input_data for select using (true);
create policy "Enable update access for all users" on input_data for update using (true);

-- V2 Updates: Detailed Analysis & Saved Reports
alter table input_data 
add column if not exists operation_info jsonb default '{}'::jsonb,
add column if not exists facility_info jsonb default '{}'::jsonb,
add column if not exists instructor_info jsonb default '{}'::jsonb,
add column if not exists student_info jsonb default '{}'::jsonb,
add column if not exists tuition_info jsonb default '{}'::jsonb;

create table if not exists saved_reports (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    input_data_id uuid references input_data(id),
    report_content jsonb default '{}'::jsonb
);

alter table saved_reports enable row level security;
create policy "Enable read access for all users" on saved_reports for select using (true);
create policy "Enable insert access for all users" on saved_reports for insert with check (true);
create policy "Enable update access for all users" on saved_reports for update using (true);
create policy "Enable delete access for all users" on saved_reports for delete using (true);
